name: Rust

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt update -y
      - name: Install cross-compile linker
        run: sudo apt install -y gcc-mingw-w64
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Add windows target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Build for GNU/Linux
        run: cargo build --verbose --profile release
      - name: Build for Windows
        run: cargo build --verbose --profile release --target x86_64-pc-windows-gnu
      - name: List artifacts
        run: ls -alh ./target/release/
      - name: Create github release and attach assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/github-learning
            target/release/github-learning.exe