name: Rust

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build release assets
        run: cargo build --verbose --profile release
      - name: Create github release and attach assets
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/*.exe
