name: Rust

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build source
        run: cargo build --verbose --profile release
      - name: Create github release and attach assets
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/^github-learning{\.exe,}$
